/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ToolbarLazyRouteImport = createFileRoute('/toolbar')()
const DefaultLazyRouteImport = createFileRoute('/default')()

const ToolbarLazyRoute = ToolbarLazyRouteImport.update({
  id: '/toolbar',
  path: '/toolbar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/toolbar.lazy').then((d) => d.Route))
const DefaultLazyRoute = DefaultLazyRouteImport.update({
  id: '/default',
  path: '/default',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/default.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/default': typeof DefaultLazyRoute
  '/toolbar': typeof ToolbarLazyRoute
}
export interface FileRoutesByTo {
  '/default': typeof DefaultLazyRoute
  '/toolbar': typeof ToolbarLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/default': typeof DefaultLazyRoute
  '/toolbar': typeof ToolbarLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/default' | '/toolbar'
  fileRoutesByTo: FileRoutesByTo
  to: '/default' | '/toolbar'
  id: '__root__' | '/default' | '/toolbar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DefaultLazyRoute: typeof DefaultLazyRoute
  ToolbarLazyRoute: typeof ToolbarLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolbar': {
      id: '/toolbar'
      path: '/toolbar'
      fullPath: '/toolbar'
      preLoaderRoute: typeof ToolbarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/default': {
      id: '/default'
      path: '/default'
      fullPath: '/default'
      preLoaderRoute: typeof DefaultLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DefaultLazyRoute: DefaultLazyRoute,
  ToolbarLazyRoute: ToolbarLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
