/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ToolbarLazyRouteImport = createFileRoute('/toolbar')()

const ToolbarLazyRoute = ToolbarLazyRouteImport.update({
  id: '/toolbar',
  path: '/toolbar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/toolbar.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/toolbar': typeof ToolbarLazyRoute
}
export interface FileRoutesByTo {
  '/toolbar': typeof ToolbarLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/toolbar': typeof ToolbarLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/toolbar'
  fileRoutesByTo: FileRoutesByTo
  to: '/toolbar'
  id: '__root__' | '/toolbar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ToolbarLazyRoute: typeof ToolbarLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolbar': {
      id: '/toolbar'
      path: '/toolbar'
      fullPath: '/toolbar'
      preLoaderRoute: typeof ToolbarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ToolbarLazyRoute: ToolbarLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
